name: 'GitHub Actions'
 
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
        with:
            python-version: 3.7
    # 执行仓库中的脚本文件
      - name: 'sign in'
        run: |
             python -m pip install --upgrade pip
             pip install requests
             pip install beautifulsoup4
             python ./user.py
      # 使用现成的发送邮箱的GitHub action来发送邮件
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
          server_address: smtp.qq.com
          server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 天气预报 
          body: aaa
          to: 3496587872@qq.com
          from: GitHub Actions
          content_type: text/html
